# Generated by Django 5.1.4 on 2025-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookReview', '0002_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('book', '本'), ('game', 'ゲーム'), ('dvd', 'DVD')], default='book', max_length=10),
        ),
    ]
